### ISSUE TITLE
[Feature][Mod Compat] Add support for create mod

### ISSUE THREAD

**Issue by ChristopherHaws** [PanSzelescik/bedcolorer#12]
Hey there! Any chance we can get support for create mod blocks? Some items that would make great candidates are:
- [Shafts](https://create.fandom.com/wiki/Shaft)
- [Casings](https://create.fandom.com/wiki/Casing)
- [Cogwheels](https://create.fandom.com/wiki/Cogwheel)

I am on fabric but create mod exists for both fabric and forge.

Thanks!

**Comment by PanSzelescik** [comment]
Hello!
Thanks for a suggestion! I looked at the Create mod and I don't quite understand how I could add support to these blocks. This mod was supposed to be very simple: color various blocks by clicking the appropriate dye. Unfortunately, I don't see colored versions of the given blocks, so I don't know what you expect

**Comment by PanSzelescik** [comment]
I'm closing this issue due to no feedback
